#!/bin/bash
#################################################
#Author: Jatin Gentela
#Version: 1.0.0
#Usage: To practice both bash scripting and git commands
#Date: 24-Aug-2023
#################################################
if [[  5 -gt 2  ]]; then
 echo "Your condition in the bash script is true"
else
 echo "Your condition in the bash script is not true. Fix your code"
fi
#Lets think this is a commit from another developer or they merged branches
for course in aws devops linux git; do
echo ${course}
done
